apiVersion: core.spinoperator.dev/v1alpha1
kind: SpinApp
metadata:
  name: rabbit-consumer 
spec:
  image: {{IMG_REPO}}
  replicas: 1
  executor: containerd-shim-spin
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-consumer
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: rabbit-consumer
